### PR TITLE
fix: add missing property in model generated

### LINKED ISSUE #899: Auto-discover auto_increment / identity field into property with generated = true and not be required
Currently, when I discover a model from a SQL Server table with an identity field or a MySQL table  auto_increment field, that model will not have that field's `generated` property set to true.

I propose to change that. So that I when I discover a table with an auto numbered field into a fresh model. I can immediately do a Model.create without getting the error message _"The `model_name` instance is not valid. Details: `primary_key_name` can't be blank (value: null)."_

What we can do to accomplish that is to alter loopback-connector-xxx/lib/queryColumns to return also a `generated` boolean to capture if a column is auto numbered by the database.

For [mssql you'd add](http://stackoverflow.com/questions/87747/how-do-you-determine-what-sql-tables-have-an-identity-column-programatically):

```
COLUMNPROPERTY(object_id(table_schema+'.'+table_name), column_name, 'IsIdentity') AS generated
```

For [mysql you'd add](http://stackoverflow.com/questions/13772019/sql-check-if-a-column-auto-increments):

```
CASE WHEN extra LIKE '%auto_increment%' THEN 1 ELSE 0 END AS generated
```

Then here in loopback-datasource-juggler/lib/datasource.js method discoverSchemas at about line 1354, You'd change this

```
schema.properties[propName] = {
  type: item.type,
  required: (item.nullable === 'N' || item.nullable === 'NO'
  || item.nullable === 0 || item.nullable === false),
  length: item.dataLength,
  precision: item.dataPrecision,
  scale: item.dataScale
};
```

to

```
schema.properties[propName] = {
  type: item.type,
  required: (item.nullable === 'N' || item.nullable === 'NO'
  || item.nullable === 0 || item.nullable === false) && !item.generated,
  length: item.dataLength,
  precision: item.dataPrecision,
  scale: item.dataScale,
  generated: item.generated
};
```

(and in discoverSchemasSync too)

What do you think?

### PR DESCRIPTION
**Pull request by aaqilniz**
Signed-off-by: Muhammad Aaqil <aaqilniz@yahoo.com>

This PR adds a missing property `generated` to the model. The issue is happening while using lb4 to discover models. Discovering a model that has a constraint of auto_increment set to true doesn't work correctly. The discovery fails to pick up the auto_increment constraint. This was happening due to the fact that `loopback-datasource-juggler` was not attaching the property to the model properties being passed to the discover generator. This PR fixes that and attaches `generated: true/false` to the model. And sets `required` to `false` if a field has `generated` set to `true`.

Fixes #899

## Checklist

- [x] [Sign off your commits](https://loopback.io/doc/en/contrib/code-contrib.html) with DCO (Developer Certificate of Origin)
- [x] `npm test` passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Review by achrinza — APPROVED** [review]
The changes LGTM :+1: Would like another maintainer's approval on this before merging (e.g. @dhmlau).

@aaqilniz Please squash the PR into 1 commit with the DCO sign-off, without any merge commits.

File: lib/datasource.js [hunk 1]
```diff
@@ -1666,11 +1666,12 @@ DataSource.prototype.discoverSchemas = function(tableName, options, cb) {
       const propName = nameMapper('column', item.columnName);
       schema.properties[propName] = {
         type: item.type,
-        required: (item.nullable === 'N' || item.nullable === 'NO' ||
+        required: item.generated ? false : (item.nullable === 'N' || item.nullable === 'NO' ||
```
Comment (samarpanB) [inline lib/datasource.js:1669]: Just to avoid ternary operator which causes cognitive complexity and difficult to understand.

```suggestion
        required: !item.generated && (item.nullable === 'N' || item.nullable === 'NO' ||
```

File: lib/datasource.js [hunk 2]
```diff
@@ -1830,10 +1832,11 @@ DataSource.prototype.discoverSchemasSync = function(modelName, options) {
     const propName = nameMapper('column', item.columnName);
     schema.properties[propName] = {
       type: item.type,
-      required: (item.nullable === 'N'),
+      required: item.generated ? false : item.nullable === 'N',
```
Comment (samarpanB) [inline lib/datasource.js:1835]:
```suggestion
      required: !item.generated && item.nullable === 'N',
```

File: test/discovery.test.js [hunk 3]
```diff
@@ -34,6 +34,7 @@ describe('Memory connector with mocked discovery', function() {
       dataPrecision: null,
       dataScale: null,
       nullable: 0,
+      generated: undefined,
```
Comment (samarpanB) [inline test/discovery.test.js:37]: Shouldn't we need to add a test case where generated is true ?

**Review by samarpanB — CHANGES_REQUESTED** [review]

**Comment by aaqilniz** [comment]
Hi @achrinza . The commits are squashed. Looking forward to getting this PR merged. 
Thanks.

**Review by samarpanB — APPROVED** [review]

**Comment by dhmlau** [comment]
LGTM. I just kicked off CI. Let's wait to see the results. Thanks.

**Comment by aaqilniz** [comment]
Thanks a lot, @dhmlau. It looks like every check has been passed and the PR can be merged.

**Comment by dhmlau** [comment]
Thanks @aaqilniz for your contribution. Your PR has been merged! 🎉
